package fr.leandremru.rickandmortylocations.data.local.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import fr.leandremru.rickandmortylocations.data.local.dao.LocationDao
import kotlinx.coroutines.Dispatchers

/**
 * Room database for the locally cached locations.
 *
 * Built from a platform-specific [RoomDatabase.Builder] provided via Koin —
 * the KMP boundary lives in [LocationsDatabaseConstructor], whose actuals
 * are generated by the Room compiler.
 */
@Database(
    entities = [LocationEntity::class],
    version = 1,
    exportSchema = false,
)
@ConstructedBy(LocationsDatabaseConstructor::class)
abstract class LocationsDatabase : RoomDatabase() {
    abstract fun locationDao(): LocationDao
}

/** Room generates the actual for every target. */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object LocationsDatabaseConstructor : RoomDatabaseConstructor<LocationsDatabase> {
    override fun initialize(): LocationsDatabase
}

/** Finalises the platform-provided builder with the bundled cross-platform SQLite driver. */
fun getLocationsDatabase(builder: RoomDatabase.Builder<LocationsDatabase>): LocationsDatabase =
    builder
        .fallbackToDestructiveMigrationOnDowngrade(true)
        .setDriver(BundledSQLiteDriver())
        .setQueryCoroutineContext(Dispatchers.Default)
        .build()
